config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :employees, only: [:index, :create, :update, :edit, :new, :destroy]
  root 'employees#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  LIST = ["Marketing", "Operations", "Finance", "Sales", "Human Resource", "Purchase"]

  validates :name, presence: true, uniqueness: true

end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department, optional: true


  def department_name
    department&.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :employee, only: [:update, :edit, :destroy]

  def index
    @employees = Employee.all.includes(:department)
  end

  def new
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
  end

  def edit
  end

  def update
    @employee.update(employee_params)
  end

  def destroy
    @employee.destroy
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email_address, :phone, :salary, :department_id)
  end

  def employee
    @employee = Employee.find_by id: params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  INDIAN_COMMA_REGEX = /(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/

  def comma_style(num, rounding: 1, precision: 2, currency_symbol: nil, style: 'indian', strip_insignificant_zeros: false)
    return '-&nbsp;&nbsp;&nbsp;'.html_safe if num.zero?
    rounded_num = (num.to_f / rounding)
    amt         = if style == 'indian'
                    number_with_precision(rounded_num.abs, precision: precision, delimiter: ',', strip_insignificant_zeros: strip_insignificant_zeros, delimiter_pattern: INDIAN_COMMA_REGEX)
                  else
                    number_with_precision(rounded_num.abs, precision: precision, delimiter: ',')
                  end
    if rounded_num.negative?
      content_tag(:span, "(#{"#{currency_symbol} " if currency_symbol}#{amt})".html_safe, style: 'color: #ed0000', class: 'negative-num').html_safe
    else
      content_tag(:span, "#{"#{currency_symbol} " if currency_symbol}#{amt}".html_safe, class: 'positive-num')
    end
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/departments/_form.html.erb
<div class="modal is-paneled-right is-active" data-id="department">
  <div class="modal-background"></div>
  <div class="modal-content" style="width: 50%">
    <div class="modal-card">
      <div class="box">
        <div class="content">
          <div class="title-enc">
            <h3><span>Update Department</span></h3>
            <div class="align-inside-title align-right" style="top:0;">
              <button class="delete" aria-label="close" data-dismiss="modal"></button>
            </div>
          </div>
          <%= form_with url: employee_path(@employee), data: {remote: true}, scope: :employee, method: :patch do |f| %>
            <div class="field">
              <p class="control">
                <label for="department_id" class="label">Choose Department</label>
                <%= f.select :department_id, options_for_select(Department.all.pluck(:name, :id)), class: "select", prompt: true %>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <%= f.submit "Save", class: "button is-success is-small" %>
              </p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/_employees.html.erb
<tr data-tr-emp-id="<%= emp.id %>">
  <td><%= emp.first_name %></td>
  <td><%= emp.last_name %></td>
  <td><%= emp.email_address %></td>
  <td><%= emp.phone %></td>
  <td class="has-text-right"><%= comma_style (emp.salary||0), precision: 0 %></td>
  <td data-td-emp-id="<%= emp.id %>">
    <% if emp.department_id.nil? %>
      <%= link_to "Edit Department", edit_employee_path(emp), data: {remote: true}, class: "button is-success has-text-weight-bold is-light is-small" %>
    <% else %>
      <%= emp.department_name %>
    <% end %>
  </td>
  <td>
    <%= link_to "Remove", employee_path(emp), method: :delete, data: {remote: true, confirm: "Are you sure?"}, class: "has-text-danger" %>
  </td>
</tr>

app/views/employees/_form.html.erb
<div class="modal is-paneled-right is-active" data-id="employees">
  <div class="modal-background"></div>
  <div class="modal-content" style="width: 50%">
    <div class="modal-card">
      <div class="box">
        <div class="content">
          <div class="title-enc">
            <h3><span>Create Employee</span></h3>
          </div>
          <%= form_with url: employees_path, data: {remote: true}, scope: :employee, method: :post do |f| %>
            <div class="field">
              <p class="control">
                <label for="department_id" class="label">First Name</label>
                <%= f.text_field :first_name, class: 'input', placeholder: 'First name', required: true %>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <label for="department_id" class="label">Last Name</label>
                <%= f.text_field :last_name, class: 'input', placeholder: 'Last name', required: true %>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <label for="department_id" class="label">Email</label>
                <%= f.text_field :email_address, class: 'input', placeholder: 'Email Address', required: true %>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <label for="department_id" class="label">Salary Amount</label>
                <%= f.text_field :salary, class: 'input', placeholder: 'Salary', required: true %>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <label for="department_id" class="label">Phone</label>
                <%= f.text_field :phone, class: 'input', placeholder: 'Phone', required: true %>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <label for="department_id" class="label">Department</label>
                <%= f.select :department_id, options_for_select(Department.all.pluck(:name, :id)), class: "select", prompt: true %>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <%= f.submit "Save", class: "button is-success is-small" %>
              </p>
            </div>
          <% end %>
        </div>
        <div class="has-text-right">
          <a data-dismiss="modal" class="button is-danger is-light">Close</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/create.js.erb
<%unless @employee.errors.any? %>
$('[data-tbody="employees"]').append("<%=j render partial:"/employees/employees",locals:{emp:@employee} %>")
$('.modal-div').html("")
<%end %>

app/views/employees/destroy.js.erb
$('[data-tr-emp-id="<%= @employee.id %>"]').remove()

app/views/employees/edit.js.erb
$('.modal-div').html("<%=j render partial:"/departments/form"%>")

app/views/employees/index.html.erb
<div class="has-text-right py-4">
  <%= link_to "Add Employee", new_employee_path, class: "button is-success  is-outlined has-text-weight-bold", data: {remote: true} %>
</div>
<table class="table is-fullwidth">
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th class="has-text-right">Salary</th>
    <th>Department</th>
    <th></th>
  </tr>
  </thead>
  <tbody data-tbody="employees">
  <%= render partial: "employees", collection: @employees, as: :emp %>
  </tbody>
</table>
<div class="modal-div">
</div>

app/views/employees/new.js.erb
$('.modal-div').html("<%= j render partial:"/employees/form" %>")

app/views/employees/update.js.erb
<%if @employee.department_name.present? %>
$('[data-td-emp-id="<%=@employee.id %>"]').text("<%=@employee.department_name %>")
$('.modal-div').html("")
<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CultureMonkey</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<nav class="navbar is-transparent">
  <div class="navbar-brand">
    <p class="navbar-item has-text-weight-bold">
      <span class="title is-3" style="color:#5dce98">Culture Monkey <span class="title is-3 has-text-black">Assignment</span></span>
    </p>
    <div class="navbar-burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
</nav>
<div class="p-6">
  <%= yield %>
</div>
</body>
</html>